### ISSUE TITLE
Lite version

### ISSUE THREAD

**Issue by andreimarin90** [andreimarin90/bbt_builder#13]
Lite version. 
1. meta pentru "light version" pe template (acesta va fi diferit de free version)
2. creem parametru ?v=free_light_version
3. checkbox cu default true de "block from light version" pe modules.
4. no d&d pe modules cu pct 3. true.; 
5. all premades inactive (se ocupa arlad) ; 
6. clasa "light-version" in body; 
7. export posibil
8. pop-up diferit pe lite version. (arlad + needs design)

**Comment by toleabivol** [comment]
1. no need, just add parameter in url (same template as full will transform in light)
2. done
3. done
4. done [atributul `disabled` added]
5. @arlad 
6. done
7. done
8. @andreimarin90 @arlad 
9. no render modules cu 3 activ in main layout - done

**Comment by andreimarin90** [comment]
moving this to a new issue.
