### ISSUE TITLE
Purchase code input & export

### ISSUE THREAD

**Issue by andreimarin90** [andreimarin90/bbt_builder#17]
1. Error : false

- sa dea warning "Please try again, your purchase code is not correct."

2. Success - Nu imi place foarte mult acest refresh de il face. Putem scapa de el si sa display direct export field below?

**Comment by toleabivol** [comment]
O sa fie less secure ... agree ?

**Comment by andreimarin90** [comment]
1. Care parte mai exact supara?
2. ce inseamna less secure?

**Comment by toleabivol** [comment]
1. Cind fac refresh se fac maimulte chestii server side care autentifica userul. Daca voi face prin JS display la un buton - cineva mai istet o sa poata repeta acelasi lucru pe alt template care nu l-a cumparat.

2. La refresh se controleaza in mai multe locuri daca e logat sau ba fa asta sau ba. Acum prin JS va trebui de avut grija si de locurile alea ceea ce implica ajax si revenim la V.2 slowness.

**Comment by andreimarin90** [comment]
Atunci lasam asa dar schimbam putin. Punem p.c si butonul de export si bagi code si cand dai click p buton face refresh si direct da pop-up de download. Asta e bn?

**Comment by andreimarin90** [comment]
E pe FTP? Nu vad schimbarea :-?  Nu stiu sigur daca ai inteles. Ideea era sa fie deja butonul de export acolo, si cand bagi PC, sa apesi pe buton si abia atunci sa se faca "send", not on enter like now.
