### ISSUE TITLE
All-In-One template

### ISSUE THREAD

**Issue by andreimarin90** [andreimarin90/bbt_builder#26]
momentan cand adaugam sectiuni ele vor intra in ordine cronologica in acel initial "all-in-one". problema e ca pt unele templates acestea nu vor avea "spatii" intre ele. Cum e si la Miaghi curent. Ca sa nu adaugam 1000 de posturi cu spatii, putem face a.i. sa creem un premade template "all" care sa fie displayed acolo, dar sa se creeze ca orice alt premade template.

**Comment by toleabivol** [comment]
Programatic nicicum ? 
Sa pun automat spatiile alea ? este o logica la ele ?

**Comment by andreimarin90** [comment]
Nu, nu este o logica la ele. Daca nu ti se pare o idee buna cea sa creem un premade template all-in-one, la ce ma mai pot gandi este sa facem la orice modul meta de "before" si "after" in care sa putem selecta un alt modul by name, care sa fie displayed either before or after by case.

**Comment by toleabivol** [comment]
Pick from layouts which one to be shown on index
