### ISSUE TITLE
Purchase VS My Items bla bla

### ISSUE THREAD

**Issue by andreimarin90** [andreimarin90/bbt_builder#3]
daca esti logat si purchase confirmed sa dispara purchase button sa ramana my items.

**Comment by toleabivol** [comment]
Daca nu esti logat si e free template ce sa arate/faca butonu ?

**Comment by andreimarin90** [comment]
hmmm...

nelogat +paid = purchase
logat + paid = my items
logat + (entirely) free = my items
nelogat + (entirely)free = Premium templates (acelasi template de la my
items duplicat si sa nu aiba sectiunea de my items).
nelogat/logat + (partially) free = purchase
